PATH_PARTS=(
    $HOME/.rd/bin # rancher desktop: nerdctl, kubectl, etc
    $HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin # yarn
    $HOME/go/bin # go
    /opt/homebrew/bin:/opt/homebrew/sbin # homebrew
    /Library/TeX/texbin # TeX
    /opt/homebrew/anaconda3/bin # Anaconda
    /usr/local/bin
)
export PATH="${(j/:/)PATH_PARTS}:$PATH"

export LESS="--no-init --quit-if-one-screen --RAW-CONTROL-CHARS"

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

export EDITOR="nvim"
# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

[ -f ~/.homebrew-github-token ] && source ~/.homebrew-github-token

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

true
