export PATH="${HOME}/bin:/opt/homebrew/bin:${HOME}/go/bin:${PATH}"

export LESS="--no-init --quit-if-one-screen --RAW-CONTROL-CHARS"

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

export EDITOR="nvim"
# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

[ -f ~/.homebrew-github-token ] && source ~/.homebrew-github-token
